## DB Config ##
spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true

  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/iot_project"
    username: springuser
    password: ThePassword
    driver-class-name: com.mysql.cj.jdbc.Driver

## Broker configuration ##
mqtt:
  broker: "tcp://broker.hivemq.com"
  clientId: "subscribe_client"
  topic: "iotProject/measurements"
  qos: 0;